[package]
name = "executor"
version = "0.1.0"
description = "OlaVM executor"
readme = "README.md"
license = "MIT"
edition = "2021"

[dependencies]
core = { package = "core", path = "../core", version = "0.1.0"}
log = "0.4"
env_logger = "0.6"
serde_json = "1"
serde = {version = "1" }
serde_derive = {version = "1"}
plonky2 = { path = "../plonky2/plonky2" }
assembler = {path="../assembler"}
interpreter = {path="../interpreter"}
criterion = "0.4"
regex = "1"
anyhow = "1.0.70"
thiserror = "1.0.40"


[[bench]]
name = "fibo_loop"
harness = false

[[bench]]
name = "sqrt_iteration"
harness = false

[[bench]]
name = "sqrt_prophet"
harness = false
